name: Client

on:
  workflow_dispatch:
  pull_request:
    paths:
      - package.json
      - client/**
    branches:
      - main
  push:
    paths:
      - client/**
    branches:
      - main

jobs:
  test:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install global dependencies
        run: npm install -g lerna @angular/cli &> /dev/null

      - name: install dependencies
        run: |
          lerna exec npm install --scope=quickstack -- --force
          lerna exec npm install --scope=client -- --force

      - name: test
        run: lerna run test:ci --scope=client
  build:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install global dependencies
        run: npm install -g lerna @angular/cli &> /dev/null

      - name: install dependencies
        run: |
          lerna exec npm install --scope=quickstack -- --force
          lerna exec npm install --scope=client -- --force

      - name: build
        run: lerna run build --scope=client
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: install globals dependencies
        run: npm install -g lerna @angular/cli &> /dev/null

      - name: install dependencies
        run: |
          lerna exec npm install --scope=quickstack
          lerna exec npm install --scope=client

      - name: build
        run: lerna run build:prod --scope=client
        working-directory: client

      - name: deploy
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: |
          docker build -t ghcr.io/kashw2/client:${{ github.sha }} -t ghcr.io/kashw2/client:latest -f Dockerfile .
          docker push ghcr.io/kashw2/client:${{ github.sha }}
          docker push ghcr.io/kashw2/client:latest
        working-directory: client