name: Client

on:
  workflow_dispatch:
  pull_request:
    paths:
      - package.json
      - client/**
    branches:
      - main
  push:
    paths:
      - client/**
    branches:
      - main

jobs:
  test:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: setup checkout
        uses: actions/checkout@v3

      - name: install global dependencies
        run: npm install -g lerna @angular/cli &> /dev/null

      - name: npm install
        run: |
          lerna exec npm install --scope=quickstack -- --force
          lerna exec npm install --scope=client -- --force

      - name: test
        run: lerna run test --scope=client -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  build:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install globals
        run: npm install -g lerna @angular/cli &> /dev/null

      - name: npm install
        run: |
          lerna exec npm install --scope=quickstack -- --force
          lerna exec npm install --scope=client -- --force
      - name: build
        run: lerna run build --scope=client